correction

diff --git a/0x0C-web_server/0-transfer_file b/0x0C-web_server/0-transfer_file
--- a/0x0C-web_server/0-transfer_file
+++ b/0x0C-web_server/0-transfer_file
@@ -1,27 +1,24 @@
-#!/usr/bin/env bash
-# checking for CLI arguments
+#!/bin/bash
 
-if [ $# -lt 4]
-then
-	echo "Usage: 0-transfer_file PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
+# Check if less than 4 parameters are passed
+if [ "$#" -lt 4 ]; then
+	echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
 	exit 1
-
 fi
-#Assigning variables
-path_to_file = $1
-ip = $2
-username = $3
-path_to_ssh_key = $4
 
-#disabling strict host key checking
+# Assign parameters to variables
+file_path="$1"
+server_ip="$2"
+username="$3"
+ssh_key="$4"
 
-scp -o "StrictHostKeyChecking=no" -i "$path_to_ssh_key" "$path_to_file" "$username@$ip:~/"
+# Transfer the file using scp with strict host key checking disabled
+scp -o StrictHostKeyChecking=no -i "$ssh_key" "$file_path" "$username@$server_ip:~/"
 
-#checking if tranfer is succesful
-
-if [$? -eq 0]
-then
-	echo"file was transfered successfully"
+# Check if scp command was successful
+if [ $? -eq 0 ]; then
+	echo "File transferred successfully."
 else
-	echo"file transfer failed"
+	echo "Error transferring file."
 fi
+
